title: 3D Vision and Modeling Challenges in eCommerce
email: qym.ustc@gmail.com
#description: Website for the Workshop on 3D Vision and Modeling Challenges in eCommerce
  ---
baseurl: "" # the subpath of your site, e.g. /blog

# Build settings
markdown: kramdown
include: ['_pages']
